import type { Bank, Entity } from "./banks-data"

export type TxCategory =
  | "receita-vendas"
  | "salario"
  | "transferencia"
  | "alimentacao"
  | "transporte"
  | "moradia"
  | "saude"
  | "educacao"
  | "lazer"
  | "material-obra"
  | "mao-de-obra"
  | "fornecedor"
  | "cartao"
  | "imposto"
  | "investimento"
  | "consorcio"
  | "fatura"
  | "outros"

export type TxAgent = "ricardo" | "marcos" | "eng" | "ana" | "diretor" | "auto" | null

export type Transaction = {
  id: string
  date: string // ISO yyyy-mm-dd
  desc: string
  meta?: string
  category: TxCategory
  agent: TxAgent
  bank: Bank
  bankLabel: string
  accountSuffix: string
  entity: Entity
  amount: number // positivo entrada, negativo saída
  conciliated?: boolean
}

export const TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    date: "2026-04-23",
    desc: "Venda Unidade 401 · entrada",
    meta: "Comprador: João Silva · NF 4521",
    category: "receita-vendas",
    agent: "diretor",
    bank: "itau",
    bankLabel: "Itaú PJ Vimar",
    accountSuffix: "45678-9",
    entity: "vimar",
    amount: 90000,
    conciliated: true,
  },
  {
    id: "t2",
    date: "2026-04-23",
    desc: "Siderúrgica SP · aço CA-50",
    meta: "NF 87234 · 1,2t · Boleto",
    category: "material-obra",
    agent: "eng",
    bank: "itau",
    bankLabel: "Itaú PJ Vimar",
    accountSuffix: "45678-9",
    entity: "vimar",
    amount: -24800,
    conciliated: true,
  },
  {
    id: "t3",
    date: "2026-04-23",
    desc: "Pix recebido · Acme Corp",
    meta: "Adiantamento proposta",
    category: "receita-vendas",
    agent: "diretor",
    bank: "itau",
    bankLabel: "Itaú PJ",
    accountSuffix: "98765-4",
    entity: "palharestech",
    amount: 15000,
    conciliated: true,
  },
  {
    id: "t4",
    date: "2026-04-23",
    desc: "Mercado Pão de Açúcar",
    meta: "Cartão Itaú Black · 1x",
    category: "alimentacao",
    agent: "auto",
    bank: "itau",
    bankLabel: "Itaú",
    accountSuffix: "12345-6",
    entity: "pf",
    amount: -487.34,
  },
  {
    id: "t5",
    date: "2026-04-22",
    desc: "Empreiteiro · folha quinzenal",
    meta: "18 colaboradores · TED",
    category: "mao-de-obra",
    agent: "eng",
    bank: "bradesco",
    bankLabel: "Bradesco PJ Obras",
    accountSuffix: "12345-0",
    entity: "vimar",
    amount: -34200,
    conciliated: true,
  },
  {
    id: "t6",
    date: "2026-04-22",
    desc: "Venda Unidade 703 · entrada",
    meta: "NF 4522",
    category: "receita-vendas",
    agent: "diretor",
    bank: "itau",
    bankLabel: "Itaú PJ Vimar",
    accountSuffix: "45678-9",
    entity: "vimar",
    amount: 90000,
    conciliated: true,
  },
  {
    id: "t7",
    date: "2026-04-22",
    desc: "Posto Shell · combustível",
    meta: "Cartão Nubank · 1x",
    category: "transporte",
    agent: "auto",
    bank: "nubank",
    bankLabel: "Nubank",
    accountSuffix: "78901-2",
    entity: "pf",
    amount: -312.5,
  },
  {
    id: "t8",
    date: "2026-04-22",
    desc: "AWS · Cloud PalharesTech",
    meta: "Fatura mensal",
    category: "fornecedor",
    agent: "diretor",
    bank: "santander",
    bankLabel: "Santander PJ",
    accountSuffix: "11223-3",
    entity: "palharestech",
    amount: -4280,
  },
  {
    id: "t9",
    date: "2026-04-21",
    desc: "Salário · José Ferreira (Contador)",
    meta: "Honorários abril",
    category: "fornecedor",
    agent: "ricardo",
    bank: "itau",
    bankLabel: "Itaú PJ",
    accountSuffix: "98765-4",
    entity: "palharestech",
    amount: -3500,
  },
  {
    id: "t10",
    date: "2026-04-21",
    desc: "Restaurante Mistura Oficial",
    meta: "Cartão Itaú · 1x · jantar",
    category: "lazer",
    agent: "auto",
    bank: "itau",
    bankLabel: "Itaú",
    accountSuffix: "12345-6",
    entity: "pf",
    amount: -284.6,
  },
  {
    id: "t11",
    date: "2026-04-21",
    desc: "Aplicação CDB Nubank · 112% CDI",
    meta: "Resgate em D+0",
    category: "investimento",
    agent: "ricardo",
    bank: "nubank",
    bankLabel: "Nubank",
    accountSuffix: "78901-2",
    entity: "pf",
    amount: -10000,
    conciliated: true,
  },
  {
    id: "t12",
    date: "2026-04-20",
    desc: "ArtCasa · esquadrias alumínio",
    meta: "NF 4421 · Bloco A",
    category: "material-obra",
    agent: "eng",
    bank: "itau",
    bankLabel: "Itaú PJ Vimar",
    accountSuffix: "45678-9",
    entity: "vimar",
    amount: -32400,
    conciliated: true,
  },
  {
    id: "t13",
    date: "2026-04-20",
    desc: "Cliente XYZ · pagamento NF 0892",
    meta: "Boleto registrado",
    category: "receita-vendas",
    agent: "diretor",
    bank: "itau",
    bankLabel: "Itaú PJ",
    accountSuffix: "98765-4",
    entity: "palharestech",
    amount: 38900,
    conciliated: true,
  },
  {
    id: "t14",
    date: "2026-04-19",
    desc: "Parcela consórcio Porto Seguro",
    meta: "Grupo 8472 · Cota 023",
    category: "consorcio",
    agent: "ricardo",
    bank: "itau",
    bankLabel: "Itaú PJ",
    accountSuffix: "12345-6",
    entity: "pf",
    amount: -3870,
    conciliated: true,
  },
  {
    id: "t15",
    date: "2026-04-19",
    desc: "DARF · IRPJ PalharesTech",
    meta: "Q1/2026",
    category: "imposto",
    agent: "marcos",
    bank: "itau",
    bankLabel: "Itaú PJ",
    accountSuffix: "98765-4",
    entity: "palharestech",
    amount: -8420,
    conciliated: true,
  },
  {
    id: "t16",
    date: "2026-04-18",
    desc: "Colégio Marista · mensalidade Mateus",
    meta: "Boleto · venc. 18/04",
    category: "educacao",
    agent: "ana",
    bank: "itau",
    bankLabel: "Itaú",
    accountSuffix: "12345-6",
    entity: "pf",
    amount: -3200,
  },
  {
    id: "t17",
    date: "2026-04-18",
    desc: "Colégio Positivo Junior · Sofia",
    meta: "Boleto · venc. 18/04",
    category: "educacao",
    agent: "ana",
    bank: "itau",
    bankLabel: "Itaú",
    accountSuffix: "12345-6",
    entity: "pf",
    amount: -2850,
  },
  {
    id: "t18",
    date: "2026-04-18",
    desc: "Nubank · fatura março",
    meta: "Pagamento integral",
    category: "fatura",
    agent: "ricardo",
    bank: "nubank",
    bankLabel: "Nubank",
    accountSuffix: "78901-2",
    entity: "pf",
    amount: -3240,
    conciliated: true,
  },
  {
    id: "t19",
    date: "2026-04-17",
    desc: "Distribuidora Braz · receita venda",
    meta: "Pedido #4521 · 30 dias",
    category: "receita-vendas",
    agent: "diretor",
    bank: "bb",
    bankLabel: "Banco do Brasil PJ",
    accountSuffix: "55512-0",
    entity: "braz",
    amount: 45200,
  },
  {
    id: "t20",
    date: "2026-04-17",
    desc: "Hidráulica Sul · materiais",
    meta: "NF 1234 · Bloco C",
    category: "material-obra",
    agent: "eng",
    bank: "itau",
    bankLabel: "Itaú PJ Vimar",
    accountSuffix: "45678-9",
    entity: "vimar",
    amount: -18000,
  },
  {
    id: "t21",
    date: "2026-04-16",
    desc: "Academia Smart Fit",
    meta: "Mensalidade · débito autom.",
    category: "saude",
    agent: "auto",
    bank: "itau",
    bankLabel: "Itaú",
    accountSuffix: "12345-6",
    entity: "pf",
    amount: -149.9,
  },
]

export const CATEGORY_LABEL: Record<TxCategory, string> = {
  "receita-vendas": "Receita",
  salario: "Salário",
  transferencia: "Transferência",
  alimentacao: "Alimentação",
  transporte: "Transporte",
  moradia: "Moradia",
  saude: "Saúde",
  educacao: "Educação",
  lazer: "Lazer",
  "material-obra": "Material obra",
  "mao-de-obra": "Mão de obra",
  fornecedor: "Fornecedor",
  cartao: "Cartão",
  imposto: "Imposto",
  investimento: "Investimento",
  consorcio: "Consórcio",
  fatura: "Fatura",
  outros: "Outros",
}

export const CATEGORY_COLOR: Record<TxCategory, string> = {
  "receita-vendas": "bg-emerald-50 text-emerald-700 border-emerald-200",
  salario: "bg-emerald-50 text-emerald-700 border-emerald-200",
  transferencia: "bg-hair-2 text-ink-2 border-hair",
  alimentacao: "bg-orange-50 text-orange-700 border-orange-200",
  transporte: "bg-blue-50 text-blue-700 border-blue-200",
  moradia: "bg-amber-50 text-amber-700 border-amber-200",
  saude: "bg-red-50 text-red-700 border-red-200",
  educacao: "bg-purple-50 text-purple-700 border-purple-200",
  lazer: "bg-pink-50 text-pink-700 border-pink-200",
  "material-obra": "bg-orange-50 text-orange-700 border-orange-200",
  "mao-de-obra": "bg-amber-50 text-amber-700 border-amber-200",
  fornecedor: "bg-hair-2 text-ink-2 border-hair",
  cartao: "bg-purple-50 text-purple-700 border-purple-200",
  imposto: "bg-red-50 text-red-700 border-red-200",
  investimento: "bg-emerald-50 text-emerald-700 border-emerald-200",
  consorcio: "bg-purple-50 text-purple-700 border-purple-200",
  fatura: "bg-hair-2 text-ink-2 border-hair",
  outros: "bg-hair-2 text-ink-2 border-hair",
}

export const AGENT_INFO_TX: Record<NonNullable<TxAgent>, { emoji: string; label: string }> = {
  ricardo: { emoji: "💰", label: "Ricardo" },
  marcos: { emoji: "🏛️", label: "Marcos" },
  eng: { emoji: "🏗️", label: "Engenheiro" },
  ana: { emoji: "🌸", label: "Ana" },
  diretor: { emoji: "🏢", label: "Diretor" },
  auto: { emoji: "⚡", label: "Auto" },
}
